//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtistAgencyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int id { get; set; }
        public Nullable<decimal> salary { get; set; }
        public Nullable<bool> assigned { get; set; }
        public Nullable<bool> completed { get; set; }
        public Nullable<bool> removed { get; set; }
    
        public virtual Concert Concert { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
