
/****** Object:  Database [agencydb2]    Script Date: 09/03/2021 23:12:36 ******/
CREATE DATABASE [agencydb2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'agencydb2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\agencydb2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'agencydb2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\agencydb2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [agencydb2] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [agencydb2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [agencydb2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [agencydb2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [agencydb2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [agencydb2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [agencydb2] SET ARITHABORT OFF 
GO
ALTER DATABASE [agencydb2] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [agencydb2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [agencydb2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [agencydb2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [agencydb2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [agencydb2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [agencydb2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [agencydb2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [agencydb2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [agencydb2] SET  DISABLE_BROKER 
GO
ALTER DATABASE [agencydb2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [agencydb2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [agencydb2] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [agencydb2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [agencydb2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [agencydb2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [agencydb2] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [agencydb2] SET RECOVERY FULL 
GO
ALTER DATABASE [agencydb2] SET  MULTI_USER 
GO
ALTER DATABASE [agencydb2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [agencydb2] SET DB_CHAINING OFF 
GO
ALTER DATABASE [agencydb2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [agencydb2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [agencydb2] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [agencydb2] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'agencydb2', N'ON'
GO
ALTER DATABASE [agencydb2] SET QUERY_STORE = OFF
GO
USE [agencydb2]
GO
/****** Object:  Table [dbo].[Actor]    Script Date: 09/03/2021 23:12:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Actor](
	[id] [int] NOT NULL,
 CONSTRAINT [PK_Actor] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Client]    Script Date: 09/03/2021 23:12:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Client](
	[id] [int] NOT NULL,
	[income] [decimal](18, 2) NULL,
 CONSTRAINT [PK_Client] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Concert]    Script Date: 09/03/2021 23:12:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Concert](
	[id] [int] NOT NULL,
	[venue] [nvarchar](50) NULL,
	[city] [nvarchar](50) NULL,
	[idMusician] [int] NULL,
 CONSTRAINT [PK_Concert] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Job]    Script Date: 09/03/2021 23:12:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Job](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[salary] [decimal](18, 2) NULL,
	[assigned] [bit] NULL,
	[completed] [bit] NULL,
	[removed] [bit] NULL,
 CONSTRAINT [PK_Job] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Movie]    Script Date: 09/03/2021 23:12:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Movie](
	[id] [int] NOT NULL,
	[title] [nvarchar](50) NULL,
	[genre] [nvarchar](50) NULL,
	[idActor] [int] NULL,
 CONSTRAINT [PK_Movie] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Musician]    Script Date: 09/03/2021 23:12:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Musician](
	[id] [int] NOT NULL,
 CONSTRAINT [PK_Musician] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 09/03/2021 23:12:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[firstName] [nvarchar](50) NULL,
	[lastName] [nvarchar](50) NULL,
	[removed] [bit] NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Actor]  WITH CHECK ADD  CONSTRAINT [FK_Actor_Client] FOREIGN KEY([id])
REFERENCES [dbo].[Client] ([id])
GO
ALTER TABLE [dbo].[Actor] CHECK CONSTRAINT [FK_Actor_Client]
GO
ALTER TABLE [dbo].[Client]  WITH CHECK ADD  CONSTRAINT [FK_Client_User] FOREIGN KEY([id])
REFERENCES [dbo].[User] ([id])
GO
ALTER TABLE [dbo].[Client] CHECK CONSTRAINT [FK_Client_User]
GO
ALTER TABLE [dbo].[Concert]  WITH CHECK ADD  CONSTRAINT [FK_Concert_Job] FOREIGN KEY([id])
REFERENCES [dbo].[Job] ([id])
GO
ALTER TABLE [dbo].[Concert] CHECK CONSTRAINT [FK_Concert_Job]
GO
ALTER TABLE [dbo].[Concert]  WITH CHECK ADD  CONSTRAINT [FK_Concert_Musician] FOREIGN KEY([idMusician])
REFERENCES [dbo].[Musician] ([id])
GO
ALTER TABLE [dbo].[Concert] CHECK CONSTRAINT [FK_Concert_Musician]
GO
ALTER TABLE [dbo].[Movie]  WITH CHECK ADD  CONSTRAINT [FK_Movie_Actor] FOREIGN KEY([idActor])
REFERENCES [dbo].[Actor] ([id])
GO
ALTER TABLE [dbo].[Movie] CHECK CONSTRAINT [FK_Movie_Actor]
GO
ALTER TABLE [dbo].[Movie]  WITH CHECK ADD  CONSTRAINT [FK_Movie_Job] FOREIGN KEY([id])
REFERENCES [dbo].[Job] ([id])
GO
ALTER TABLE [dbo].[Movie] CHECK CONSTRAINT [FK_Movie_Job]
GO
ALTER TABLE [dbo].[Musician]  WITH CHECK ADD  CONSTRAINT [FK_Musician_Client] FOREIGN KEY([id])
REFERENCES [dbo].[Client] ([id])
GO
ALTER TABLE [dbo].[Musician] CHECK CONSTRAINT [FK_Musician_Client]
GO
USE [master]
GO
ALTER DATABASE [agencydb2] SET  READ_WRITE 
GO
